### ISSUE TITLE
uos 系统uos id使用youqu框架方法无法登陆

### ISSUE THREAD

**Issue by wanghaiyang001** [linuxdeepin/deepin-autotest-framework#17]
环境：专业版1060update2 wayland 架构
问题描述：商店触发登陆uos id，使用"input_message"方法无法向输入框输入账号密码，走到此步骤“"kill -9 $(pidof wayland_autotool)"，登陆弹框就会卡死在那，光标消失
![image](https://github.com/linuxdeepin/deepin-autotest-framework/assets/153248500/27fa1282-5aa6-4320-9e3a-702a17529cb6)

**Comment by mikigo** [comment]
先用 `press_key()` 方法代替 `input_message()` 在这里输入吧；
