### ISSUE TITLE
auto_uos安装问题

### ISSUE THREAD

**Issue by akaroka** [linuxdeepin/deepin-autotest-framework#27]
最近在做 aarch64架构+wayland的UOS系统自动化
auto_uos这个工具是闭源的不，根据文档在执行env.sh的时候提示安装失败，查看sh脚本内部的镜像地址似乎是一个内网地址~ 
这个库是有另外独立发布嘛，感谢解答~

**Comment by mikigo** [comment]
auto_uos 是统信公司内部的一个业务层公共库，目前还没有做开源，这个库的作用是提供了一些公共的元素操作方法，比如在任务栏点击某个图标，可以减少子项目编写和维护方法的工作量；

**Comment by akaroka** [comment]
OK, 感谢解答~
