### ISSUE TITLE
CSV跳过用例规则新增

### ISSUE THREAD

**Issue by zhao-george** [linuxdeepin/deepin-autotest-framework#29]
目前csv跳过用例可以按照多种条件进行跳过，但是这些条件不能并列执行，只能跳过单一条件，是否可以支持多个条件并行跳过。

**Comment by mikigo** [comment]
https://github.com/linuxdeepin/deepin-autotest-framework/commit/81d837ee86c23f24d75197a335dad0d1a10f6293
